### ISSUE TITLE
Restore khodiyAr mAtA to /devatA/shakti/

### ISSUE THREAD

**Issue by vvasuki** [jyotisham/adyatithi#11]
Recently, the khodiyAr mAtA event was moved from /devatA/shakti/ to mahApuruSha/general-indic-non-tropical/ .

This is wrong, since, despite being associated with some (non-historically attested) human birth story, she's considered a deity. So, it is fit to regard her as an devI, an avatAra - like rAma or kRShNa or vaiShNo devI or panjurli . 

This move may have been motivated by disinterest in that deity (on part of one's religious community), and the desire to have a calendar without such. But rather than eroding the meaningfulness of the repo organization, this should be solved by other means as mentioned in https://github.com/jyotisham/jyotisha/issues/136 .

**Comment by karthikraman** [comment]
No, no - it was not at all motivated by removing the festival. I was trying to carefully correct the organisation of various festivals. In fact, all these repos are part of my regular calendar generation.

Looks like I was wrong to conclude that this would be in the same bracket as agrasen maharaj etc. being a daughter of a king. Clearly, the sources refer to her as a form of the Goddess. Will revert.
