### ISSUE TITLE
Replace `\n` in strings with multi-line strings

### ISSUE THREAD

**Issue by karthikraman** [jyotisham/adyatithi#5]
I presume this is OK @vvasuki ? It will greatly improve readability...

**Comment by vvasuki** [comment]
> I presume this is OK @vvasuki ? It will greatly improve readability...

Definitely!

**Comment by karthikraman** [comment]
Was there an issue with this that you fixed via da49730a6f0a96948a78514b0ab5d9e9a0c7af4f?

**Comment by vvasuki** [comment]
shloka fields and some description fields which needed correction
