### ISSUE TITLE
folder organisation changed?

### ISSUE THREAD

**Issue by karthikraman** [jyotisham/adyatithi#8]
Not sure when this happened, but now I find festivals as under `lunar_month/tithi/month_num/tithi_num` whereas it used to be `lunar_month/month_num/tithi/tithi_num`. Is the present organisation more advantageous in some way?

**Comment by vvasuki** [comment]
I don't recall changing it - so must be pretty long back. In any case, it is superior since it conforms to REST API standards. Running jyotisha/jyotisha/panchaanga/temporal/festival/rules/__init__.py automatically fixes rule paths (which in the distant past tended to be a bit haphazard).
